version: "3"
networks:
  tareaSD:
    ipam:
      driver: default
      config:
        - subnet: 172.1.1.0/24

services:
  headnode:
    build:
      context: ./headnode
      dockerfile: Dockerfile
    command: python3 /headnode/headnode.py
    volumes:
      - ./headnode:/headnode/
    networks:
      tareaSD:
        ipv4_address: "172.1.1.10"
    ports:
      - "5000:5000"

  datanode1:
    build:
      context: ./datanode1
      dockerfile: Dockerfile
    command: python3 /datanode1/datanode1.py
    volumes:
      - ./datanode1:/datanode1/
    networks:
      tareaSD:
        ipv4_address: "172.1.1.11"
    depends_on:
      - headnode

  datanode2:
    build:
      context: ./datanode2
      dockerfile: Dockerfile
    command: python3 /datanode2/datanode2.py
    volumes:
      - ./datanode2:/datanode2/
    networks:
      tareaSD:
        ipv4_address: "172.1.1.12"
    depends_on:
      - headnode

  datanode3:
    build:
      context: ./datanode3
      dockerfile: Dockerfile
    command: python3 /datanode3/datanode3.py
    volumes:
      - ./datanode3:/datanode3/
    networks:
      tareaSD:
        ipv4_address: "172.1.1.13"
    depends_on:
      - headnode

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    command: python3 /client/client.py
    volumes:
      - ./client:/client/
    networks:
      tareaSD:
        ipv4_address: "172.1.1.20"
    depends_on:
      - headnode
      - datanode1
      - datanode2
      - datanode3
